### ISSUE TITLE
Android - Integration - Display Timed Activities

### ISSUE THREAD

**Issue by ceceliacreates** [WomenWhoCode/WWCodeMobile#185]
Integrate the logic created in #75 to the UI created in #65.

**Comment by ThanaReka** [comment]
Hi @baghaii @gaurigadkari. Looking to work on a new issue now that my PR #254 has been approved.  I thought I'd pick this one up since I've worked on both the logic and UI for this issue before, but not sure what else needs to be done for this integration.  Please let me know what needs to be done for this issue and whether I can work on it?

**Comment by baghaii** [comment]
I assigned you this one 

The TaskListViewModel needs to be updated to take in the flow that gets all the tasks from the repo and display them on the screen. You will probably need

**Comment by renweview** [comment]
how's it going on this one! @ThanaReka
