### ISSUE TITLE
Android - Bug - TimeUtil crash

### ISSUE THREAD

**Issue by baghaii** [WomenWhoCode/WWCodeMobile#280]
The convertDateToMillis function in the TimeUtil class will cause a crash if the input is not a properly formatted date, catch the ParseException like in the calculateDuration function in the same file.

## If a PR already exists, link it to this issue
* See [how to manually link the pull request to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue-using-the-pull-request-sidebar)

## Get yourself assigned to this issue
* If you want to work on this issue, request to have it be assigned to you by:
1. Add a comment that you want to work on the issue
2. Tag a maintainer to request assignment

**Comment by ThanaReka** [comment]
@baghaii @gaurigadkari @renweview I'd like to submit a PR for this issue, if it's not too late. It's the last bug related issue so thought I'd give it a shot (I've already worked out the code in my local copy of the project so it won't take too long to submit a PR).  Let me know if it can be assigned, or otherwise no worries.
